/*  +---------------------------------------------------------------------------+
*  |                                                                           |
*  | Fluicell AB, http://fluicell.com/                                         |
*  | Lab-on-a-tip 2.0                                                          |
*  |                                                                           |
*  | Authors: Mauro Bellone - http://www.maurobellone.com                      |
*  | Released under GNU GPL License.                                           |
*  +---------------------------------------------------------------------------+ */


#ifndef Labonatip_macroWizard_H_
#define Labonatip_macroWizard_H_

// standard libraries
#include <iostream>

// autogenerated form header
#include "ui_Lab-on-a-tip_macroWizard.h"

// Qt
#include <QtWidgets>
#include <QDateTime>


using namespace std;

class Labonatip_macroWizard : public QDialog
{
    Q_OBJECT

public:
	explicit Labonatip_macroWizard(QWidget *parent = 0);

	~Labonatip_macroWizard() {}

	void setMacroPath(QString _path) { m_macro_path = _path; }

	void setSolNames(QString _name1, QString _name2, QString _name3, QString _name4)
	{
		m_name_sol1 = _name1;
		m_name_sol2 = _name2;
		m_name_sol3 = _name3;
		m_name_sol4 = _name4;
	}

	void setDefPreVac(int _p_on_def, int _p_off_def, int _v_rec_def, int _v_sw_def)
	{
		m_p_on_def = _p_on_def;
		m_p_off_def = _p_off_def;
		m_v_rec_def = _v_rec_def;
		m_v_sw_def = _v_sw_def;
	}

private slots:
	
	void next_page1to2();

	void next_page2to();

	void next();

	void back();

	bool save();

	void exit();
	
	void closeEvent(QCloseEvent *event);


private:

	QString m_macro_path;

	void setBanner(int _current_index);

	QString m_protocol_name;

	QString m_name_sol1;
	QString m_name_sol2;
	QString m_name_sol3;
	QString m_name_sol4;

	int m_p_on_def;
	int m_p_off_def;
	int m_v_rec_def;
	int m_v_sw_def;

protected:
	Ui::Labonatip_macroWizard *ui_wizard;    //!<  the user interface
};

#endif /* Labonatip_macroWizard_H_ */