/*  +---------------------------------------------------------------------------+
*  |                                                                           |
*  | Fluicell AB, http://fluicell.com/                                         |
*  | Lab-on-a-tip 2.0                                                          |
*  |                                                                           |
*  | Authors: Mauro Bellone - http://www.maurobellone.com                      |
*  | Released under GNU GPL License.                                           |
*  +---------------------------------------------------------------------------+ */


#ifndef Labonatip_macroWizard_H_
#define Labonatip_macroWizard_H_

// standard libraries
#include <iostream>

// autogenerated form header
#include "ui_macroWizard.h"

// Qt
#include <QtWidgets>
#include <QDateTime>

#include "toolDataStructures.h"

using namespace std;

class Labonatip_macroWizard : public QDialog
{
    Q_OBJECT

public:
	explicit Labonatip_macroWizard(QWidget *parent = 0);

	~Labonatip_macroWizard() {}

	void setMacroPath(QString _path) { m_macro_path = _path; }

	void setSolParams(solutionsParams _params) {
		*m_solutionParams = _params; 
		updateSolPrFields();
	}

	void setPrParams(pr_params _params) { 
		*m_pr_params = _params; 
	updateSolPrFields();
	}

signals:
	void loadSettings();  // generated when loadsettings is pressed

private slots:
	
	void next_page1to2();

	void next_page2to();

	void next();

	void back();

	bool save();

	void exit();
	
	void closeEvent(QCloseEvent *event);


private:

	QString m_macro_path;

	void setBanner(int _current_index);

	QString m_protocol_name;

	void updateSolPrFields();

	solutionsParams *m_solutionParams;
	pr_params *m_pr_params;

protected:
	Ui::Labonatip_macroWizard *ui_wizard;    //!<  the user interface
};

#endif /* Labonatip_macroWizard_H_ */